uploads = []
outputs = []

[[generated]]
id = "ppqpUULxfVtznRGAONSCe"
uri = "file://artifacts/dino-battle/src/assets/velociraptor.png"
type = "image"
title = "cartoon velociraptor"

[[generated]]
id = "gR-eAcCoGYS9uoNT3yWEN"
uri = "file://artifacts/dino-battle/src/assets/giganotosaurus.png"
type = "image"
title = "cartoon giganotosaurus"

[[generated]]
id = "SxOkDK5t2hM7wjbSYZo_7"
uri = "file://artifacts/dino-battle/src/assets/spinosaurus.png"
type = "image"
title = "cartoon spinosaurus"

[[generated]]
id = "LdNX8pNZurbRrXlyuIr7v"
uri = "file://artifacts/dino-battle/src/assets/forest-bg.png"
type = "image"
title = "pokemon style battle arena"

[[generated]]
id = "qoBc7gpzfAjyRXWe0WwHM"
uri = "file://attached_assets/generated_images/tyrannosaurus_rex_dinosaur_cel_48a1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ng6GsTf6KpenY7pxa6A9k"
uri = "file://attached_assets/generated_images/tyrannosaurus_rex_dinosaur_cel_8ffe.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ht3YNQbzdEQXV974KGRIw"
uri = "file://attached_assets/generated_images/pterodactylus_pterosaur_dinosaur_cel_fdfe.png"
type = "image"
title = "generated_image"

[[generated]]
id = "GaJ88JPsWjJTQq3Ydw74D"
uri = "file://artifacts/dino-battle/src/assets/arena-bg.png"
type = "image"
title = "jungle arena background"

[[generated]]
id = "j-X_n1uuqcX3EAohnfLJd"
uri = "file://artifacts/dino-battle/src/assets/trex.png"
type = "image"
title = "cartoon trex"

[[generated]]
id = "4B0AedIj_FrKvJI9WkJoJ"
uri = "file://artifacts/dino-battle/src/assets/pterodactylus.png"
type = "image"
title = "cartoon pterodactyl flock"
