uploads = []
outputs = []

[[generated]]
id = "ppqpUULxfVtznRGAONSCe"
uri = "file://artifacts/dino-battle/src/assets/velociraptor.png"
type = "image"
title = "velociraptor accurate game art"

[[generated]]
id = "gR-eAcCoGYS9uoNT3yWEN"
uri = "file://artifacts/dino-battle/src/assets/giganotosaurus.png"
type = "image"
title = "giganotosaurus accurate game art"

[[generated]]
id = "SxOkDK5t2hM7wjbSYZo_7"
uri = "file://artifacts/dino-battle/src/assets/spinosaurus.png"
type = "image"
title = "spinosaurus accurate game art"

[[generated]]
id = "LdNX8pNZurbRrXlyuIr7v"
uri = "file://artifacts/dino-battle/src/assets/forest-bg.png"
type = "image"
title = "pokemon style battle arena"
